name: runall the commands

on: 
  push

jobs: 
  run-shell-command:
  runs-on: ubuntu-latest
  steps:
    - name: run the commands
      run: echo " this is our first simple actions workflow"
        